spring.application.name=tribalcrafts-backend

spring.datasource.url=jdbc:mysql://localhost:3306/tribal_crafts_db
spring.datasource.username=root
spring.datasource.password=Sriram2007*

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Gemini API Key
app.gemini.api-key=AIzaSyDvX7egsNWmMLgH6pqdDrHeF3BL0iDOcAs

server.port=8081